species: Arabidopsis thaliana

seq_info:
  type: Resequencing
  mode: PE
  replicate: 1

path: /home/xfu/Project/HYH/XGK/YHH0022/SHOREmapping/fastq/

samples:
  - M7-9
  - bri1-5

foreground:
  - M7-9

background:
  - bri1-5

index: /home/xfu/Gmatic5/genome/tair10/tair10
chrSizes: /home/xfu/Gmatic5/genome/tair10/tair10.chromSize
genome: //home/xfu/Gmatic5/genome/tair10/tair10.fa
gff: tair10_fix.gff

cpu: 30

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

samtools: /home/xfu/Gmatic5/bin/samtools-0.1.19/samtools

bcftools: /home/xfu/Gmatic5/bin/samtools-0.1.19/bcftools/bcftools

shoremap: /home/xfu/Git/SHOREmapping/software/SHOREmap
